# This is a config for E2B sandbox template.
# You can use template ID (ckskh5feot2y94v5z07d) or template name (smart-forge-fullstack) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("smart-forge-fullstack") # Sync sandbox
# sandbox = await AsyncSandbox.create("smart-forge-fullstack") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('smart-forge-fullstack')

team_id = "b660529a-e319-48aa-be6d-3cbd73c07878"
start_cmd = "compile_fullstack.sh"
dockerfile = "e2b-fullstack.Dockerfile"
template_name = "smart-forge-fullstack"
template_id = "ckskh5feot2y94v5z07d"
