# This is a config for E2B sandbox template.
# You can use template ID (qol4m59jq6av3h13gt3h) or template name (smartforge-api-sandbox-v1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("smartforge-api-sandbox-v1") # Sync sandbox
# sandbox = await AsyncSandbox.create("smartforge-api-sandbox-v1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('smartforge-api-sandbox-v1')

team_id = "2d4e0ab4-6730-490a-b7d1-01e7ede65814"
start_cmd = "/bin/true"
dockerfile = "e2b.Dockerfile"
template_name = "smartforge-api-sandbox-v1"
template_id = "qol4m59jq6av3h13gt3h"
